(()=>{'use strict';
const tg=window.Telegram?.WebApp,$=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],fmt=n=>Number(n).toLocaleString('ru-RU'),date=t=>new Date(t*1000).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
let activeCase=null,openCount=1,owned=[];
let user=null,catalog=[],tickets=[],selected=null,tab='cases',filter='all',chatSignature='';
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function message(text){$('#notice').textContent=text;$('#notice').hidden=!text}
async function api(path,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);let r;try{r=await fetch('/api/tg/'+path,{signal:controller.signal,method:data===undefined?'GET':'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})})}finally{clearTimeout(timer)}let j;try{j=await r.json()}catch{throw Error('Сервер недоступен. Попробуй позже')}if(!r.ok){const err=Error(j.error||'Ошибка сервера');err.status=r.status;throw err;}return j}
function safe(fn){return async e=>{e?.preventDefault();const target=e?.currentTarget;const buttons=target?.tagName==='FORM'?[...target.querySelectorAll('button')]:target?.tagName==='BUTTON'?[target]:[];if(buttons.some(b=>b.disabled))return;buttons.forEach(b=>b.disabled=true);try{message('');await fn(e)}catch(err){message(err.message||'Проверь подключение к интернету')}finally{buttons.forEach(b=>b.disabled=false)}}}
function button(text,fn,cls='text-button'){const b=el('button',text,cls);b.type='button';b.onclick=safe(fn);return b}
function input(name,placeholder,type='text'){const n=el('input');n.name=name;n.placeholder=placeholder;n.type=type;n.required=true;n.setAttribute('aria-label',placeholder);return n}
function empty(root,text){root.replaceChildren(el('p',text,'muted'))}
function balance(b){$('#bal').textContent=fmt(b);$('#serverBalance').textContent=fmt(b)}
async function refreshMe(){const j=await api('me');user=j.user;if(!user)throw Error('Сессия истекла. Открой приложение заново через Telegram');balance(user.balance);$('#starsBuy').disabled=!user.stars_enabled;$('#starsStatus').textContent=user.stars_enabled?'Начисление после подтверждения Telegram':'Пополнение пока недоступно';$('#name').textContent=user.first_name||user.username||'Игрок';$('#tid').textContent=(user.username?'@'+user.username+' · ':'')+'ID '+user.tg_id;$('#avatar').textContent=(user.first_name||user.username||'M')[0];$('#adminTab').hidden=!user.is_admin;if(user.banned)throw Error('Аккаунт заблокирован. '+user.ban_reason)}
async function history(){const j=await api('history'),root=$('#history');root.replaceChildren();if(!j.events.length)return empty(root,'Пока нет операций');j.events.forEach(x=>{const row=el('div',undefined,'history-row'),label=el('div',x.reason);label.append(el('small',date(x.created)));row.append(label,el('strong',(x.delta>0?'+':'')+fmt(x.delta)+' ◆'));root.append(row)})}
async function show(id){if(!['cases','upgrade','profile','support','admin'].includes(id))return;if(id==='admin'&&!user?.is_admin)return;tab=id;all('.view').forEach(v=>v.hidden=v.id!==id);all('#tabs [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));tg?.HapticFeedback?.selectionChanged();if(id==='cases')tg?.BackButton?.hide();else tg?.BackButton?.show();window.scrollTo(0,0);if(!user)return;if(id==='profile'){await refreshMe();await history();await inventory()}if(id==='upgrade')await inventory();if(id==='support')await refreshTickets();if(id==='admin')await refreshAdmin()}
all('[data-tab]').forEach(b=>b.onclick=safe(()=>show(b.dataset.tab)));$('.brand').onclick=safe(()=>show('cases'));
function caseImage(img,c){img.src='assets/'+(c.image||('case-'+c.id+'.png'));img.alt=c.name;img.loading='lazy';img.onerror=()=>{img.onerror=null;img.src='assets/image-fallback.svg'}}
function renderLoot(c){const items=new Map((window.MESH_ITEMS||[]).map(p=>[p.id,p]));const root=$('#detailLoot');root.replaceChildren();[...c.drops].sort((a,b)=>(items.get(a[0])?.value||0)-(items.get(b[0])?.value||0)).forEach(([id,chance])=>{const p=items.get(id),card=el('article',undefined,'loot-card');if(!p){card.append(el('strong','Предмет недоступен'));root.append(card);return}const img=el('img');img.src='assets/'+p.img;img.alt=p.name;img.loading='lazy';img.onerror=()=>{img.onerror=null;img.src='assets/image-fallback.svg'};card.dataset.tier=p.value>=c.price*3?'top':p.value>=c.price?'profit':'base';card.append(el('span',fmt(chance)+'%','loot-chance'),img,el('strong',p.name),el('small',(p.duration||'')+(p.imagePending?' · Изображение пока недоступно':''),'muted'),el('b',fmt(p.value)+' ◆'));root.append(card)})}
const categoryNames={server:'Серверы',client:'Клиенты',allin:'ALL IN'};
function renderCases(){const query=$('#caseSearch').value.trim().toLocaleLowerCase('ru');const list=catalog.filter(c=>(filter==='all'||c.type===filter)&&(!query||c.name.toLocaleLowerCase('ru').includes(query)));$('#caseCount').textContent=list.length+' кейсов';$('#caseGrid').replaceChildren();const groups=new Map();for(const type of [...Object.keys(categoryNames),...new Set(list.map(c=>c.type))]){if(groups.has(type))continue;const cases=list.filter(c=>c.type===type);if(!cases.length)continue;const section=el('section',undefined,'catalog-group'),heading=el('h3',categoryNames[type]||'Другие кейсы'),grid=el('div',undefined,'case-grid');heading.append(el('span',String(cases.length),'muted'));section.append(heading,grid);$('#caseGrid').append(section);groups.set(type,grid)}list.forEach(c=>{const card=el('button',undefined,'case-card');card.type='button';const img=el('img');caseImage(img,c);const price=el('div','◆ '+fmt(c.price),'price');price.append(el('span','↗'));card.style.setProperty('--case-accent',c.accent||'#b6ff55');card.append(el('span',({server:'Сервер',client:'Клиент',allin:'All-in'})[c.type],'category'),img,el('strong',c.name),el('small',c.drops.length+' предметов · до '+fmt(c.metrics.maxValue)+' ◆','muted'),price);card.onclick=()=>{activeCase=c;openCount=c.type==='allin'?10:1;renderCounts();$('#openResult').textContent='';$('#detailTitle').textContent=c.name;$('#detailPrice').textContent=fmt(c.price)+' монет ◆';caseImage($('#detailImage'),c);renderLoot(c);const info=el('p',(c.type==='allin'?'ALL IN: дешёвые предметы или редкий топ-приз, без промежуточного дропа. ':'')+'Предметов: '+c.drops.length+' · Минимум: '+fmt(c.metrics.minValue)+' ◆ · Максимум: '+fmt(c.metrics.maxValue)+' ◆ · Шанс предмета от цены кейса: '+fmt(c.metrics.profitChance)+'%. Окупаемость не гарантирована.','loot-summary');$('#detailLoot').prepend(info);$('#caseDialog').showModal();tg?.HapticFeedback?.selectionChanged()};groups.get(c.type).append(card)});if(!list.length)empty($('#caseGrid'),query?'Ничего не найдено. Измени запрос или категорию.':'В этой категории пока нет кейсов')}
$('#caseSearch').addEventListener('input',renderCases);
all('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;all('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));renderCases()});$('#closeCase').onclick=()=>$('#caseDialog').close();

function pendingKey(){return 'meshcase-pending-'+user.tg_id}
let gameBusy=false;
async function gameAction(action,data){
 if(gameBusy)throw Error("Дождись завершения текущей операции");
 gameBusy=true;
 try{return await executeGameAction(action,data)}catch(e){window.MeshFX?.error(e.message);throw e}finally{gameBusy=false}
}
async function executeGameAction(action,data){
 if(!user)throw Error('Войди через Telegram');
 let pending=JSON.parse(localStorage.getItem(pendingKey())||'null');
 if(pending && action)throw Error('Сначала проверь незавершённую операцию в профиле');
 if(!pending){if(!action)return;pending={action,data:{...data,request_id:crypto.randomUUID()}};localStorage.setItem(pendingKey(),JSON.stringify(pending))}
 window.MeshFX?.waiting(pending.action);
 let j;try{j=await api('game/'+pending.action,pending.data)}catch(e){if(e.status>=400&&e.status<500){localStorage.removeItem(pendingKey());throw e;}throw Error(e.message+' · Ключ сохранён. Проверь операцию в профиле; не повторяй списание вручную.')}
 localStorage.removeItem(pendingKey());balance(j.balance);
 const text=j.action==='open'&&j.count>1?'Открыто '+j.count+' кейсов · Все предметы в инвентаре':j.action==='sell_all'?'Продано '+j.count+' предметов · +'+fmt(j.total)+' ◆':j.action==='sell'?'Предмет продан':j.action==='upgrade'&&!j.success?'Апгрейд не удался. Исходный предмет израсходован.':'Получен: '+j.prize.item.name+' · '+fmt(j.prize.item.value)+' ◆';
 try{await window.MeshFX?.result(j,catalog)}catch{window.MeshFX?.error(text)}
 $('#openResult').textContent=text;message(text);
 try{await refreshMe();await inventory();await history()}catch{message(text+' · Не удалось обновить профиль. Нажми «Обновить»; операция уже выполнена.')}return j;
}
$('#openCase').onclick=safe(async()=>{if(!activeCase) return;$('#openResult').textContent='Открываем…';try{await gameAction('open',{case_id:activeCase.id,count:openCount})}catch(e){$('#openResult').textContent=e.message;throw e}});
$('#retryGame').onclick=safe(()=>gameAction(null));
async function inventory(){
 const j=await api('game/inventory'),root=$('#inventory');owned=j.inventory;$('#sellAllInventory').disabled=!owned.length;$('#sellAllInventory').textContent='Продать всё · '+fmt(owned.reduce((n,x)=>n+x.item.value,0))+' ◆';renderUpgrade();root.replaceChildren();
 if(!j.inventory.length)empty(root,'Пока нет предметов');
 const ids=new Set(catalog.flatMap(c=>c.drops.map(d=>d[0])));
 j.inventory.forEach(x=>{const card=el('div',undefined,'card inventory-item'),img=el('img');img.src='assets/'+x.item.img;img.alt='';img.loading='lazy';img.onerror=()=>{img.onerror=null;img.src='assets/image-fallback.svg'};card.append(img,el('strong',x.item.name+' · '+fmt(x.item.value)+' ◆'));
 card.append(button('Продать за '+fmt(x.item.value)+' ◆',async()=>{if(confirm('Продать предмет за внутренние монеты?'))await gameAction('sell',{inventory_id:x.id})}));
 card.append(button('В апгрейд',async()=>{await show('upgrade');$('#upgradeSource').value=String(x.id);renderTargets()}));root.append(card);
 });
 $('#gameHistory').replaceChildren(...j.operations.map(o=>el('p',({open:'Открытие',sell:'Продажа',sell_all:'Продажа всех',upgrade:'Апгрейд'})[o.action]+': '+(o.action==='open'&&o.count>1?o.count+' кейсов':(o.action==='sell_all'?o.count+' предметов · '+fmt(o.total)+' ◆':null)||o.prize?.item.name||(o.action==='sell'?o.source.name:'Неудача')))));
}

function renderCounts(){
 $('#openCounts').replaceChildren(...(activeCase.type==='allin'?[10,25,50,100]:[1,2,3,5,10]).map(n=>{const b=button(String(n),()=>{openCount=n;renderCounts()},n===openCount?'selected':'text-button');b.setAttribute('aria-pressed',String(n===openCount));return b}));
 $('#openCase').textContent='Открыть ×'+openCount+' · '+fmt(activeCase.price*openCount)+' ◆';
}
function preview(root,p){root.replaceChildren();if(!p){root.append(el('p','Выбери предмет ниже','muted'));return;}const img=el('img');img.src='assets/'+p.img;img.alt=p.name;img.className='upgrade-image';img.onerror=()=>{img.onerror=null;img.src='assets/image-fallback.svg'};root.append(img,el('p',p.name+' · '+fmt(p.value)+' ◆'))}
function source(){return owned.find(x=>String(x.id)===$('#upgradeSource').value)}
function targets(){const x=source(),ids=new Set(catalog.flatMap(c=>c.drops.filter(d=>d[1]>0).map(d=>d[0])));return x?(window.MESH_ITEMS||[]).filter(p=>ids.has(p.id)&&p.value>x.item.value&&Math.floor(x.item.value*900000/p.value)>=100).sort((a,b)=>a.value-b.value):[]}
function renderUpgrade(){const select=$('#upgradeSource'),old=select.value;select.replaceChildren(...owned.map(x=>{const o=el('option',x.item.name+' · '+fmt(x.item.value)+' ◆ (#'+x.id+')');o.value=x.id;return o}));if(owned.some(x=>String(x.id)===old))select.value=old;renderTargets()}
function renderTargets(){const select=$('#upgradeTarget'),old=select.value;select.replaceChildren(...targets().map(p=>{const o=el('option',p.name+' · '+fmt(p.value)+' ◆');o.value=p.id;return o}));if(targets().some(p=>p.id===old))select.value=old;renderChance()}
function renderChance(){const x=source(),p=targets().find(p=>p.id===$('#upgradeTarget').value);preview($('#sourcePreview'),x?.item);preview($('#targetPreview'),p);$('#performUpgrade').disabled=!x||!p;const chance=x&&p?Math.floor(x.item.value*900000/p.value)/10000:0;$('#chanceValue').textContent=fmt(chance)+'%';$('#chanceRing').style.setProperty('--chance',chance+'%');renderPickerGrids();$('#upgradeChance').textContent=x&&p?'Шанс: '+fmt(Math.floor(x.item.value*900000/p.value)/10000)+'%. При неудаче предмет сгорает.':x?'Нет доступной цели':'Нет предметов. Сначала открой кейс.'}
function renderPickerGrids(){
 const draw=(root,list,selected,choose)=>{root.replaceChildren();if(!list.length){empty(root,'Нет доступных предметов');return;}list.forEach(x=>{const b=button('',()=>choose(String(x.id)),'upgrade-choice');b.setAttribute('aria-pressed',String(String(x.id)===selected));preview(b,x.item||x);root.append(b)})};
 draw($('#sourceGrid'),owned,$('#upgradeSource').value,id=>{$('#upgradeSource').value=id;renderTargets()});
 const q=$('#targetSearch').value.trim().toLowerCase();draw($('#targetGrid'),targets().filter(p=>p.name.toLowerCase().includes(q)),$('#upgradeTarget').value,id=>{$('#upgradeTarget').value=id;renderChance()});
}
$('#targetSearch').oninput=renderPickerGrids;
async function sellBatch(items){if(!items.length)return;const total=items.reduce((n,x)=>n+x.item.value,0);if(!confirm('Продать '+items.length+' предметов за '+fmt(total)+' внутренних монет?'))return;return gameAction('sell_all',{inventory_ids:items.map(x=>x.id)})}
$('#sellAllInventory').onclick=safe(()=>sellBatch([...owned]));
window.MeshSellBatch=sellBatch;
$('#upgradeSource').onchange=renderTargets;$('#upgradeTarget').onchange=renderChance;
all('#upgradePresets button').forEach(b=>b.onclick=()=>{const x=source(),list=targets();if(!x||!list.length)return;const goal=b.dataset.mult?x.item.value*Number(b.dataset.mult):x.item.value*90/Number(b.dataset.chance);const p=list.reduce((best,p)=>Math.abs(p.value-goal)<Math.abs(best.value-goal)?p:best);$('#upgradeTarget').value=p.id;renderChance()});
$('#performUpgrade').onclick=safe(async()=>{const x=source(),p=targets().find(p=>p.id===$('#upgradeTarget').value);if(!x||!p)return;if(confirm($('#upgradeChance').textContent+' Продолжить?'))await gameAction('upgrade',{inventory_id:x.id,target_id:p.id})});

$('#redeem').onsubmit=safe(async e=>{const f=e.currentTarget;const j=await api('redeem',{code:f.elements.code.value});balance(j.balance);f.reset();await history();message('Промокод активирован — монеты начислены');tg?.HapticFeedback?.notificationOccurred('success')});
$('#starsForm').onsubmit=safe(async()=>{if(!user?.stars_enabled)throw Error('Пополнение пока недоступно');if(!tg?.openInvoice)throw Error('Открой приложение через Telegram');const j=await api('invoice',{stars:Number($('#starsPack').value)});tg.openInvoice(j.url,status=>{if(status==='paid'){message('Telegram принял оплату. Проверяем начисление…');let tries=0;const poll=setInterval(async()=>{try{await refreshMe();await history();if(++tries>=5){clearInterval(poll);message('История обновлена. Если начисление задерживается, напиши в поддержку.')}}catch{clearInterval(poll)}},2000)}else message(status==='cancelled'?'Оплата отменена':'Статус платежа: '+status)})});
$('#refreshProfile').onclick=safe(async()=>{await refreshMe();await history();await inventory()});
function bubble(m){const b=el('div',undefined,'bubble'+(m.staff?' staff':''));b.append(el('small',m.staff?'Команда MeshCase':'Игрок'),el('div',m.body));const t=el('time',date(m.created));t.dateTime=new Date(m.created*1000).toISOString();b.append(t);return b}
function renderChat(){const t=tickets.find(x=>x.id===selected);if(!t){selected=null;$('#chat').hidden=true;$('#supportHome').hidden=false;return}$('#supportHome').hidden=true;$('#chat').hidden=false;$('#chatTitle').textContent='Обращение #'+t.id;$('#ticketStatus').textContent=t.status==='open'?'Закрыть':'Открыть';$('#chatForm').hidden=t.status==='closed';const signature=JSON.stringify(t.messages);if(signature!==chatSignature){$('#messages').replaceChildren(...t.messages.map(bubble));$('#messages').scrollTop=$('#messages').scrollHeight;chatSignature=signature}}
async function refreshTickets(){const j=await api('tickets');tickets=j.tickets;const root=$('#ticketList');root.replaceChildren();if(!tickets.length)empty(root,'Обращений пока нет. Если нужна помощь — напиши нам выше.');tickets.forEach(t=>{const b=button('',()=>{selected=t.id;chatSignature='';renderChat()},'card ticket-item');b.append(el('strong','Обращение #'+t.id),el('p',t.messages.at(-1)?.body||t.body),el('span',t.status==='open'?'Открыто':'Закрыто','badge'+(t.status==='closed'?' closed':'')),el('small',' · '+date(t.created),'muted'));root.append(b)});if(selected)renderChat()}
$('#ticket').onsubmit=safe(async e=>{const f=e.currentTarget;await api('tickets',{body:f.elements.body.value});f.reset();await refreshTickets();selected=tickets[0]?.id;renderChat()});$('#refreshSupport').onclick=safe(refreshTickets);$('#backTickets').onclick=()=>{selected=null;$('#chat').hidden=true;$('#supportHome').hidden=false};$('#chatForm').onsubmit=safe(async e=>{const f=e.currentTarget;await api('tickets/message',{id:selected,body:f.elements.body.value});f.reset();await refreshTickets()});$('#ticketStatus').onclick=safe(async()=>{const t=tickets.find(x=>x.id===selected);await api('tickets/status',{id:selected,status:t.status==='open'?'closed':'open'});await refreshTickets()});
all('[data-panel]').forEach(b=>b.onclick=()=>{all('.admin-panel').forEach(p=>p.hidden=p.id!==b.dataset.panel);all('[data-panel]').forEach(x=>x.classList.toggle('selected',x===b))});
function playerCard(u){const card=el('article',undefined,'card'),head=el('div',undefined,'player-head'),identity=el('div');identity.append(el('strong',u.first_name||u.username||'Игрок'),el('small',(u.username?'@'+u.username+' · ':'')+'ID '+u.tg_id,'muted'));head.append(identity,el('strong',fmt(u.balance)+' ◆','amount'));card.append(head);if(u.banned)card.append(el('p','Заблокирован: '+u.ban_reason,'danger'));
const f=el('form',undefined,'player-form'),row=el('div',undefined,'inline'),delta=input('delta','Сумма: + / −','number'),reason=input('reason','Причина изменения');delta.min=-1000000;delta.max=1000000;reason.minLength=3;reason.maxLength=200;const submit=el('button','Изменить','primary');row.append(delta,submit);f.append(row,reason);f.onsubmit=safe(async()=>{const value=Number(delta.value);if(!window.confirm((value>=0?'Начислить ':'Списать ')+fmt(Math.abs(value))+' монет игроку ID '+u.tg_id+'?'))return;await api('admin/balance',{tg_id:u.tg_id,delta:value,reason:reason.value});await refreshAdmin();await refreshMe();message('Баланс обновлён')});card.append(f);
const banForm=el('form',undefined,'player-form');const banReason=input('reason','Причина блокировки');banReason.minLength=3;banReason.maxLength=200;if(!u.banned)banForm.append(banReason);const ban=el('button',u.banned?'Снять бан':'Заблокировать','text-button danger');banForm.append(ban);banForm.onsubmit=safe(async()=>{if(!window.confirm((u.banned?'Снять бан с ':'Заблокировать ')+u.tg_id+'?'))return;await api('admin/ban',{tg_id:u.tg_id,banned:!u.banned,reason:banReason.value});await refreshAdmin()});card.append(banForm);return card}
function adminTicket(t){const card=el('article',undefined,'card');card.append(el('h2','#'+t.id+' · '+(t.username?'@'+t.username:t.tg_id)),el('span',t.status==='open'?'Открыто':'Закрыто','badge'));const messages=el('div',undefined,'messages');messages.append(...t.messages.map(bubble));card.append(messages);if(t.status==='open'){const f=el('form',undefined,'composer'),a=el('textarea');a.required=true;a.maxLength=2000;a.placeholder='Ответ игроку…';a.setAttribute('aria-label','Ответ на обращение #'+t.id);f.append(a,el('button','Ответить','primary'));f.onsubmit=safe(async()=>{await api('admin/reply',{id:t.id,answer:a.value});await refreshAdmin()});card.append(f)}card.append(button(t.status==='open'?'Закрыть обращение':'Открыть заново',async()=>{await api('tickets/status',{id:t.id,status:t.status==='open'?'closed':'open'});await refreshAdmin()}));return card}
async function refreshAdmin(){const q=$('#userSearch').elements.q.value.trim(),j=await api('admin?q='+encodeURIComponent(q));$('#adminPayments').replaceChildren(...j.payments.map(p=>{const n=el('div',undefined,'card');n.append(el('strong',p.stars+' ⭐ → '+p.credit+' ◆'),el('p','ID '+p.tg_id+' · '+(p.charge_id?'Зачислено':'Не оплачен')),el('small',date(p.created)));return n}));if(!j.payments.length)empty($('#adminPayments'),'Платежей пока нет');$('#userCount').textContent=fmt(j.stats.users);$('#openCount').textContent=fmt(j.stats.open);$('#userList').replaceChildren(...j.users.map(playerCard));if(!j.users.length)empty($('#userList'),'Игроки не найдены');$('#promos').replaceChildren(...j.promos.map(p=>{const card=el('div',undefined,'card');card.append(el('h2',p.code),el('p',(p.kind==='balance'?fmt(p.amount)+' монет':p.amount+'%')+' · '+p.used+' / '+p.uses_limit+' активаций'),el('span',p.active?'Включён':'Выключен','badge'));if(p.expires)card.append(el('p','До '+date(p.expires)));card.append(button(p.active?'Выключить':'Включить',async()=>{await api('admin/toggle',{code:p.code,active:!p.active});await refreshAdmin()}));return card}));if(!j.promos.length)empty($('#promos'),'Промокодов ещё нет');$('#adminTickets').replaceChildren(...j.tickets.map(adminTicket));if(!j.tickets.length)empty($('#adminTickets'),'Обращений пока нет');$('#auditList').replaceChildren(...j.audit.map(a=>{const n=el('div',undefined,'card audit-entry');const names={balance:'Изменение баланса',ban:'Блокировка / разблокировка',promo_create:'Создание промокода',promo_toggle:'Статус промокода',ticket:'Работа с обращением'};n.append(el('strong',names[a.action]||a.action),el('p','Объект: '+a.target+' · Администратор: '+a.actor),el('div',a.details),el('small',date(a.created),'muted'));return n}));if(!j.audit.length)empty($('#auditList'),'Действий пока нет')}
$('#refreshAdmin').onclick=safe(refreshAdmin);$('#userSearch').onsubmit=safe(refreshAdmin);$('#createPromo').onsubmit=safe(async e=>{const f=e.currentTarget,v=f.elements;await api('admin/promo',{code:v.code.value,amount:Number(v.amount.value),limit:Number(v.limit.value),expires:v.expires.value?Math.floor(new Date(v.expires.value).getTime()/1000):0});f.reset();await refreshAdmin();message('Промокод создан')});
async function init(){try{const r=await fetch('cases.json');if(!r.ok)throw Error();catalog=(await r.json()).filter(c=>['server','client','allin'].includes(c.type));renderCases()}catch{empty($('#caseGrid'),'Не удалось загрузить каталог. Перезапусти приложение.')}
if(!tg?.initData){$('#authNotice').hidden=false;return}tg.ready();tg.expand();tg.setHeaderColor?.('#0c1018');tg.setBackgroundColor?.('#0c1018');tg.BackButton?.onClick(()=>{safe(async()=>{if($('#caseDialog').open){$('#caseDialog').close();return}if(tab==='support'&&selected){$('#backTickets').click();return}await show('cases')})()});await api('auth',{initData:tg.initData});await refreshMe();const initial=location.hash.slice(1);if(initial)await show(initial);}
safe(init)();setInterval(()=>{if(user&&!user.banned&&tab==='support'&&!document.hidden)refreshTickets().catch(e=>message(e.message))},15000);
})();
